# Indexing, Slicing, and Iterating

In [2]:
import numpy as np

In [3]:
a = np.arange(10, 16)

In [4]:
a

array([10, 11, 12, 13, 14, 15])

In [5]:
a[4]

14

In [6]:
a[-1]

15

In [7]:
a[[0, 2, 4]]

array([10, 12, 14])

In [11]:
A = np.arange(0, 9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
A[1, 1] = 4
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
a[1 : 4]

array([11, 12, 13])

In [19]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
A[:, 0]

array([0, 3, 6])

In [21]:
A[1:, 1:]

array([[4, 5],
       [7, 8]])

In [23]:
M = np.random.randint(0, 10, size=(5, 6))
M

array([[9, 8, 6, 2, 4, 2],
       [6, 0, 6, 6, 0, 3],
       [4, 8, 4, 4, 3, 1],
       [5, 2, 9, 1, 1, 2],
       [8, 8, 5, 2, 1, 4]])

In [25]:
M[2:4, 2:5]

array([[4, 4, 3],
       [9, 1, 1]])

In [27]:
M[[2, 4], 1:4]

array([[8, 4, 4],
       [8, 5, 2]])

In [29]:
for row in M:
    print(row)

[9 8 6 2 4 2]
[6 0 6 6 0 3]
[4 8 4 4 3 1]
[5 2 9 1 1 2]
[8 8 5 2 1 4]


In [32]:
np.array(M.flat)

array([9, 8, 6, 2, 4, 2, 6, 0, 6, 6, 0, 3, 4, 8, 4, 4, 3, 1, 5, 2, 9, 1,
       1, 2, 8, 8, 5, 2, 1, 4])

In [33]:
np.array(M.ravel())

array([9, 8, 6, 2, 4, 2, 6, 0, 6, 6, 0, 3, 4, 8, 4, 4, 3, 1, 5, 2, 9, 1,
       1, 2, 8, 8, 5, 2, 1, 4])

In [36]:
np.array(M.flat) == np.array(M.ravel())

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [38]:
M.ravel()

array([9, 8, 6, 2, 4, 2, 6, 0, 6, 6, 0, 3, 4, 8, 4, 4, 3, 1, 5, 2, 9, 1,
       1, 2, 8, 8, 5, 2, 1, 4])

In [44]:
list(map((lambda x: x**2), M))

[array([81, 64, 36,  4, 16,  4], dtype=int32),
 array([36,  0, 36, 36,  0,  9], dtype=int32),
 array([16, 64, 16, 16,  9,  1], dtype=int32),
 array([25,  4, 81,  1,  1,  4], dtype=int32),
 array([64, 64, 25,  4,  1, 16], dtype=int32)]

In [45]:
np.array(list(map((lambda x: x**2), M)))

array([[81, 64, 36,  4, 16,  4],
       [36,  0, 36, 36,  0,  9],
       [16, 64, 16, 16,  9,  1],
       [25,  4, 81,  1,  1,  4],
       [64, 64, 25,  4,  1, 16]], dtype=int32)

In [47]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
np.apply_along_axis(np.sum, axis=0, arr=A)

array([ 9, 12, 15])

In [51]:
np.apply_along_axis(np.sum, axis=1, arr=A)

array([ 3, 12, 21])

In [56]:
def func(x):
    return x + 2

In [57]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
np.apply_along_axis(func, axis=1, arr=A)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [59]:
np.apply_along_axis((lambda x: np.sin(x)+2), axis=1, arr=A)

array([[2.        , 2.84147098, 2.90929743],
       [2.14112001, 1.2431975 , 1.04107573],
       [1.7205845 , 2.6569866 , 2.98935825]])

In [60]:
np.apply_along_axis((lambda x: np.sin(x)+2), axis=0, arr=A)

array([[2.        , 2.84147098, 2.90929743],
       [2.14112001, 1.2431975 , 1.04107573],
       [1.7205845 , 2.6569866 , 2.98935825]])

---

# Conditions and Boolean Arrays

In [61]:
A = np.random.randn(4, 4)

In [62]:
A < 0.5

array([[ True, False, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True]])

In [64]:
A[A < 0.5]

array([-0.27631415, -0.31621194, -0.69793415, -1.01322442, -0.20510652,
       -0.3804195 , -1.82740784,  0.46316619, -0.34209464, -1.19025824,
       -0.71407674])

In [67]:
a = np.array([1, 2, 3, 4])

In [71]:
a[[True, False, True, True]]

array([1, 3, 4])

---

# Shape Manipulation

In [72]:
a = np.random.random(12)

In [73]:
a.reshape(6, 2)

array([[0.86674441, 0.90958835],
       [0.16217044, 0.61826836],
       [0.58983992, 0.04634036],
       [0.41650705, 0.62839467],
       [0.34907626, 0.93601737],
       [0.42537473, 0.20982694]])

In [74]:
a.reshape(3, 4)

array([[0.86674441, 0.90958835, 0.16217044, 0.61826836],
       [0.58983992, 0.04634036, 0.41650705, 0.62839467],
       [0.34907626, 0.93601737, 0.42537473, 0.20982694]])

In [78]:
a.shape = (3, 4)
a

array([[0.86674441, 0.90958835, 0.16217044, 0.61826836],
       [0.58983992, 0.04634036, 0.41650705, 0.62839467],
       [0.34907626, 0.93601737, 0.42537473, 0.20982694]])

In [81]:
a = a.ravel()

In [82]:
a.shape

(12,)

In [84]:
A = a.reshape(3, 4)
A

array([[0.86674441, 0.90958835, 0.16217044, 0.61826836],
       [0.58983992, 0.04634036, 0.41650705, 0.62839467],
       [0.34907626, 0.93601737, 0.42537473, 0.20982694]])

In [86]:
A.shape = (12)
A

array([0.86674441, 0.90958835, 0.16217044, 0.61826836, 0.58983992,
       0.04634036, 0.41650705, 0.62839467, 0.34907626, 0.93601737,
       0.42537473, 0.20982694])

In [88]:
A = A.reshape(3, 4)

In [89]:
A.transpose()

array([[0.86674441, 0.58983992, 0.34907626],
       [0.90958835, 0.04634036, 0.93601737],
       [0.16217044, 0.41650705, 0.42537473],
       [0.61826836, 0.62839467, 0.20982694]])

In [90]:
A.T

array([[0.86674441, 0.58983992, 0.34907626],
       [0.90958835, 0.04634036, 0.93601737],
       [0.16217044, 0.41650705, 0.42537473],
       [0.61826836, 0.62839467, 0.20982694]])

---

# Array Manipulation

In [92]:
A = np.random.randint(0, 10, size=(3, 3))
B = np.random.randn(3, 3)

In [94]:
np.vstack((A, B))

array([[ 2.        ,  5.        ,  6.        ],
       [ 8.        ,  1.        ,  0.        ],
       [ 9.        ,  8.        ,  6.        ],
       [-0.60100583,  1.33119256, -0.08139497],
       [-1.77101622, -1.21675019,  0.42150353],
       [-0.53676224,  1.96487561,  0.91666011]])

In [95]:
np.hstack((A, B))

array([[ 2.        ,  5.        ,  6.        , -0.60100583,  1.33119256,
        -0.08139497],
       [ 8.        ,  1.        ,  0.        , -1.77101622, -1.21675019,
         0.42150353],
       [ 9.        ,  8.        ,  6.        , -0.53676224,  1.96487561,
         0.91666011]])

Used only for one-dimensional array

In [97]:
a = np.arange(0, 5)
b = np.random.randint(0, 10, size=5)
c = np.random.randint(-10, 0, size=5)

In [98]:
np.column_stack((a, b, c))

array([[ 0,  5, -4],
       [ 1,  0, -1],
       [ 2,  1, -7],
       [ 3,  5, -5],
       [ 4,  8, -1]])

In [99]:
np.row_stack((a, b, c))

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  1,  5,  8],
       [-4, -1, -7, -5, -1]])

In [133]:
A = np.arange(0, 16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
# has to be split equally
[A1, A2] = np.vsplit(A, 2)
print(A1)
print(A2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [108]:
[A3, A4] = np.hsplit(A, 2)
print(A3)
print(A4)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [134]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [142]:
A = np.random.randint(0, 10, size=(4, 4))
A

array([[0, 6, 5, 7],
       [7, 1, 5, 8],
       [2, 9, 9, 5],
       [5, 1, 5, 2]])

In [143]:
A = np.vstack((A, np.random.randint(0, 10, size=(2, 4))))
A

array([[0, 6, 5, 7],
       [7, 1, 5, 8],
       [2, 9, 9, 5],
       [5, 1, 5, 2],
       [8, 5, 9, 5],
       [5, 3, 7, 3]])

In [144]:
A = np.hstack((A, np.random.randint(0, 10, size=(6, 2))))
A

array([[0, 6, 5, 7, 0, 6],
       [7, 1, 5, 8, 7, 9],
       [2, 9, 9, 5, 5, 3],
       [5, 1, 5, 2, 8, 3],
       [8, 5, 9, 5, 8, 7],
       [5, 3, 7, 3, 5, 8]])

In [145]:
A

array([[0, 6, 5, 7, 0, 6],
       [7, 1, 5, 8, 7, 9],
       [2, 9, 9, 5, 5, 3],
       [5, 1, 5, 2, 8, 3],
       [8, 5, 9, 5, 8, 7],
       [5, 3, 7, 3, 5, 8]])

In [147]:
B = np.random.randint(0, 10, (6, 6))
B

array([[2, 1, 3, 0, 7, 3],
       [9, 4, 9, 9, 4, 8],
       [6, 2, 5, 3, 4, 1],
       [6, 9, 7, 0, 9, 5],
       [3, 3, 0, 1, 8, 1],
       [0, 2, 5, 4, 4, 3]])

In [148]:
np.concatenate((A, B))

array([[0, 6, 5, 7, 0, 6],
       [7, 1, 5, 8, 7, 9],
       [2, 9, 9, 5, 5, 3],
       [5, 1, 5, 2, 8, 3],
       [8, 5, 9, 5, 8, 7],
       [5, 3, 7, 3, 5, 8],
       [2, 1, 3, 0, 7, 3],
       [9, 4, 9, 9, 4, 8],
       [6, 2, 5, 3, 4, 1],
       [6, 9, 7, 0, 9, 5],
       [3, 3, 0, 1, 8, 1],
       [0, 2, 5, 4, 4, 3]])

In [149]:
np.concatenate((A, B), axis=1)

array([[0, 6, 5, 7, 0, 6, 2, 1, 3, 0, 7, 3],
       [7, 1, 5, 8, 7, 9, 9, 4, 9, 9, 4, 8],
       [2, 9, 9, 5, 5, 3, 6, 2, 5, 3, 4, 1],
       [5, 1, 5, 2, 8, 3, 6, 9, 7, 0, 9, 5],
       [8, 5, 9, 5, 8, 7, 3, 3, 0, 1, 8, 1],
       [5, 3, 7, 3, 5, 8, 0, 2, 5, 4, 4, 3]])

In [150]:
A

array([[0, 6, 5, 7, 0, 6],
       [7, 1, 5, 8, 7, 9],
       [2, 9, 9, 5, 5, 3],
       [5, 1, 5, 2, 8, 3],
       [8, 5, 9, 5, 8, 7],
       [5, 3, 7, 3, 5, 8]])

In [151]:
[A1, A2, A3] = np.split(A, [2, 4], axis=0)

In [152]:
A1

array([[0, 6, 5, 7, 0, 6],
       [7, 1, 5, 8, 7, 9]])

In [153]:
A3

array([[8, 5, 9, 5, 8, 7],
       [5, 3, 7, 3, 5, 8]])

In [154]:
[A4, A5] = np.split(A, [3], axis=1)

In [155]:
A4

array([[0, 6, 5],
       [7, 1, 5],
       [2, 9, 9],
       [5, 1, 5],
       [8, 5, 9],
       [5, 3, 7]])

In [156]:
A5

array([[7, 0, 6],
       [8, 7, 9],
       [5, 5, 3],
       [2, 8, 3],
       [5, 8, 7],
       [3, 5, 8]])

---

# Important Points

object.flat: return flat object <br>
object.ravel: return array of flattened matrix <br>
apply_along_axis: apply some function in certain axis; parameter: func, axis, arr <br>
Indexing and slicing: A[2], A[2:3], A[2, 3], A[2:3, 4:5], A[A < 5], A[any boolean array] <br>
Reshape and Transpose: a.reshape, a.T or a.transpose <br>
Concatenate: stack, hstack, vstack, concatenate, preferable: concatenate, stack <br>
Split: split, vsplit(must the same size), hsplit(must the same size) <br>