# Ndarray: The Heart of the Library

In [1]:
import numpy as np

The whole Numpy library is based on one main object: ndarray (N-dimensional array). This object is multidimensional homogeneous array with a predetermined number of items. The datatype is specified by another Numpy object called dtype; each ndarray is associated with only one type of dtype.

The number of the dimensions and items in an array is defined by its shape, a tuple of N-positive
integers that specifies the size for each dimension. The dimensions are defined as axes and the number of
axes as rank.

In [2]:
a = np.array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int32')

In [5]:
print(a.ndim) # dimension
print(a.size) # the number of elements
print(a.shape)

1
3
(3,)


In [6]:
b = np.array([[1, 2, 3],
              [3, 4, 5]])

In [7]:
print(b.ndim)
print(b.size)
print(b.shape)
print(b.dtype)

2
6
(2, 3)
int32


In [8]:
print(a.itemsize)
print(a.data)

4


In [9]:
c = np.array([[1, 2, 3],
              [4, 5, 6]])
d = np.array(((1, 3, 5),
              (2, 4, 6)))

In [10]:
d

array([[1, 3, 5],
       [2, 4, 6]])

In [11]:
e = np.array([['a', 'b'],
              ['c', 'd']])
print(e.dtype)
print(e.dtype.name)

<U1
str32


In [12]:
f = np.array([[1, 2, 3], 
              [4, 5, 6]], dtype=complex)

In [13]:
a1 = np.array([[1, 2, 3], 
              [4, 5, 6]], dtype='float32')
b1 = np.array([[1, 2, 3], 
              [4, 5, 6]], dtype='complex')
print(a1)
print(b1)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [14]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(5, 55, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53])

In [20]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [21]:
np.arange(0, 1, 0.1).reshape(5, 2)

array([[0. , 0.1],
       [0.2, 0.3],
       [0.4, 0.5],
       [0.6, 0.7],
       [0.8, 0.9]])

In [22]:
np.arange(0, 1, 0.1).reshape(2, 5)

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

In [23]:
np.arange(0, 1, 0.1).reshape(-1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [24]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [25]:
np.linspace(1, 10, 10).reshape(2, 5)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [26]:
np.random.random(100)

array([0.12457782, 0.00269034, 0.35466236, 0.6083214 , 0.85788477,
       0.47656108, 0.10558104, 0.82255117, 0.97293705, 0.27006635,
       0.37733784, 0.90818303, 0.67483745, 0.24217123, 0.61108551,
       0.91026697, 0.18121913, 0.98669281, 0.37688606, 0.58190004,
       0.56682889, 0.05759005, 0.871877  , 0.47056138, 0.50979682,
       0.81984068, 0.28527419, 0.46334847, 0.09747928, 0.61874484,
       0.59429149, 0.30658759, 0.33961851, 0.35149537, 0.47450732,
       0.49579691, 0.76758983, 0.8214316 , 0.25875522, 0.94123545,
       0.28041755, 0.93796335, 0.35279387, 0.26304602, 0.1819783 ,
       0.13538645, 0.36317696, 0.08074046, 0.06768773, 0.02244684,
       0.40210105, 0.11440893, 0.81465752, 0.85132666, 0.53555404,
       0.84859418, 0.70904677, 0.70312183, 0.24410774, 0.44142531,
       0.11884947, 0.70470332, 0.96343485, 0.32158213, 0.79908307,
       0.20103057, 0.08768012, 0.34516666, 0.03599406, 0.44461596,
       0.5512284 , 0.64213926, 0.38813252, 0.5521086 , 0.93542

In [27]:
np.random.random((3, 3))

array([[0.7005043 , 0.76014259, 0.53484565],
       [0.15546175, 0.10235774, 0.82352844],
       [0.80492587, 0.35216399, 0.67164505]])

In [28]:
np.random.randn(2, 3)

array([[-0.93335031, -0.59269596, -0.18437751],
       [ 0.55390808, -2.13147722,  0.14330844]])

In [29]:
np.full(3, 'a')

array(['a', 'a', 'a'], dtype='<U1')

In [30]:
np.full(5, 'sekar')

array(['sekar', 'sekar', 'sekar', 'sekar', 'sekar'], dtype='<U5')

---

#  Basic Operations

## Arithmetic Operations.
Element-wise operation:

In [31]:
a = np.arange(0, 10)

In [32]:
a + 4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [33]:
a * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
b = np.linspace(0, 9, 10)
b * np.sin(b)

array([ 0.        ,  0.84147098,  1.81859485,  0.42336002, -3.02720998,
       -4.79462137, -1.67649299,  4.59890619,  7.91486597,  3.70906637])

In [35]:
A = np.arange(0, 9).reshape(3, 3)

In [36]:
B = np.eye(3)

In [37]:
A * B

array([[0., 0., 0.],
       [0., 4., 0.],
       [0., 0., 8.]])

## The Matrix Product

In [38]:
# matrix product, with dot() function
np.dot(A, B)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [39]:
A.dot(B)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [40]:
B.dot(A)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## Increment and Decrement Operators

In [41]:
a = np.arange(4)

In [42]:
for i in range(5):
    a += 1

In [43]:
a

array([5, 6, 7, 8])

## Universal Functions (ufunc)

In [44]:
a = np.arange(1, 5)

In [45]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [46]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [47]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Aggregate Functions

Aggregate functions are those functions that perform an operation on a set of values, an array for example, and produce a single result.

In [48]:
a = np.random.randn(10)

In [49]:
a

array([-0.39623192, -1.0293947 , -0.81246821, -0.53743817,  0.32456811,
        0.2338303 ,  0.04620614, -1.08346635, -0.91145349, -0.14189844])

In [50]:
np.sum(a)

-4.307746736812594

In [51]:
a.sum()

-4.307746736812594

In [52]:
a.mean()

-0.4307746736812594

In [53]:
a.std()

0.4996866440828769

---

# Important Points

Aggregate function: sum, mean, median <br>
Array creation: np.array, np.ones, np.zeros, np.eye, np.full, np.random.randint <br>
Array attributes: ndim, shape, size, dtype, 