# Numpy Tutorial

## Import Libs

In [0]:
import numpy as np

## The Basics

In [2]:
a = np.array([0, 1, 2])
print(a)

[0 1 2]


In [3]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
# Get Dimension
print("a dimension: ", a.ndim)
print("b dimension: ", b.ndim)

a dimension:  1
b dimension:  2


In [8]:
# Get data type
print('a dtype: ', a.dtype)
print('b dtype: ', b.dtype)

a dtype:  int64
b dtype:  int64


In [9]:
# Get the shape
print('a.shape: ', a.shape)
print('b.shape: ', b.shape)

a.shape:  (3,)
b.shape:  (2, 4)


In [11]:
# Get size
print('a.size: ', a.size)
print('b.size: ', b.size)

a.size:  3
b.size:  8


In [13]:
# Get total size
print('Total size: ', a.nbytes)
print('Total size: ', b.nbytes)

Total size:  24
Total size:  64


## Accessing/Changing specific elements, rows, columns, etc

In [14]:
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
# Get specific element
print(a[1, 2])

7


In [21]:
# Get specific row
print(a[0, :])      # First row
print(a[:, 1])      # Second col
print(a[1:4:2, :])

[0 1 2 3 4]
[1 6]
[[5 6 7 8 9]]


In [22]:
a[0, 0] = 10
print(a)

[[10  1  2  3  4]
 [ 5  6  7  8  9]]


In [25]:
a[:, 1] = 5
print(a)

[[10  5  2  3  4]
 [ 5  5  7  8  9]]


## Initializing Different Types of Arrays

In [28]:
# All zeros
print(np.zeros(5))
print(np.zeros((3, 4)))

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
# All ones
print(np.ones(5))
print(np.ones((3, 4)))

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
# Any other number
print(np.full((2, 3), 99))

[[99 99 99]
 [99 99 99]]


In [31]:
print(np.full_like(a, 99))

[[99 99 99 99 99]
 [99 99 99 99 99]]


In [33]:
# Random Decimal Numbers from 0 to 1
print(np.random.rand(3, 4))

[[0.5511444  0.73219941 0.29346444 0.93946917]
 [0.71467554 0.18060751 0.52704763 0.35828875]
 [0.70204162 0.65711885 0.43001276 0.26036436]]


In [35]:
print(np.random.random_sample(a.shape))

[[0.90033724 0.23157455 0.56596699 0.06562415 0.07465085]
 [0.83813531 0.96247636 0.0739483  0.31438636 0.20507378]]


In [39]:
# Random integer values
np.random.randint(1, 10, size=(3, 4))

array([[1, 9, 3, 5],
       [6, 8, 9, 7],
       [3, 5, 1, 4]])

In [40]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
# Repeat an array
arr = np.array([[1, 2, 3]])
np.repeat(arr, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [44]:
# Challenge
output = np.ones((5, 5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
output[1:-1, 1:-1] = 0
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
output[2, 2] = 9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [0]:
# Copying an array
a = np.array([1, 2, 3])
b = a.copy()

In [49]:
print(a)
b[0] = 10
print(b)

[1 2 3]
[10  2  3]


## Basic Arithmetics

In [0]:
a = np.random.randint(0, 10, (3, 4))

In [52]:
print(a)

[[5 1 1 5]
 [1 0 4 9]
 [3 6 5 0]]


In [53]:
print(a + 2)

[[ 7  3  3  7]
 [ 3  2  6 11]
 [ 5  8  7  2]]


## Linear Algebra

In [55]:
a = np.random.randint(0, 10, (3, 4))
b = np.full((4, 3), 3)
print(a)
print(b)

[[6 8 6 5]
 [9 6 0 2]
 [6 1 8 1]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


In [56]:
np.matmul(a, b)

array([[75, 75, 75],
       [51, 51, 51],
       [48, 48, 48]])

In [58]:
np.linalg.det(np.matmul(a, b))

0.0

## Statistics

In [60]:
mat = np.arange(0, 20).reshape(4, 5)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [61]:
np.min(mat, axis=0)

array([0, 1, 2, 3, 4])

In [62]:
np.min(mat, axis=1)

array([ 0,  5, 10, 15])

In [63]:
np.sum(mat)

190

In [65]:
np.sum(mat, axis=0)
np.sum(mat, axis=1)

array([10, 35, 60, 85])

## Organizing Array

In [66]:
rand = np.random.randint(0, 10, (3, 4))
print(rand)

[[4 8 9 2]
 [1 9 2 7]
 [9 1 4 1]]


In [67]:
rand.reshape(4, 3)

array([[4, 8, 9],
       [2, 1, 9],
       [2, 7, 9],
       [1, 4, 1]])

In [68]:
rand.reshape(-1)

array([4, 8, 9, 2, 1, 9, 2, 7, 9, 1, 4, 1])

In [70]:
# Vertically Stacking Vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
print(np.vstack([v1, v2]))

[[1 2 3 4]
 [5 6 7 8]]


In [71]:
# Horizontally Stacking Vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
print(np.hstack([v1, v2]))

[1 2 3 4 5 6 7 8]
